# 编译
FROM --platform=$TARGETPLATFORM debian:buster-slim as builder
WORKDIR /code
# 安装依赖
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update -y
RUN apt install -y --no-install-recommends build-essential cmake autoconf libtool pkg-config
RUN apt install -y --no-install-recommends libprotobuf-dev libgrpc++-dev protobuf-compiler protobuf-compiler-grpc wget
RUN rm -rf /var/lib/apt/lists/*

# ssl依赖
ADD http://www.openssl.org/source/openssl-1.0.1g.tar.gz
RUN tar -zxvf openssl-1.0.1g.tar.gz
WORKDIR /code/openssl-1.0.1g
RUN ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
RUN make
RUN make install
WORKDIR /code
RUN rm -rf openssl-1.0.1g

# 源码依赖
COPY pbschema /code/pbschema
COPY thirdpart /code/thirdpart
# cmake模块
COPY cmake /code/cmake
COPY CMakeLists.txt /code/CMakeLists.txt
# 源码
COPY src /code/src
# 编译
RUN cmake .
RUN make


# 压缩
FROM --platform=$TARGETPLATFORM debian:buster-slim as upx
WORKDIR /code
# 安装依赖
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update -y && \
    apt install -y --no-install-recommends build-essential cmake autoconf libtool pkg-config upx-ucl && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /code/bin/cpptestgrpc .
# 压缩
RUN mkdir bin
RUN upx --best --lzma -o /code/bin/cpptestgrpc cpptestgrpc

# 部署
FROM --platform=$TARGETPLATFORM scratch as bin
COPY --from=upx /code/bin/cpptestgrpc .
# 赋予执行权限
ENTRYPOINT  ["./cpptestgrpc"]
