// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: echo.proto

#include "echo.pb.h"
#include "echo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace echo {

static const char* ECHO_RPC_method_names[] = {
  "/echo.ECHO_RPC/echo",
};

std::unique_ptr< ECHO_RPC::Stub> ECHO_RPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ECHO_RPC::Stub> stub(new ECHO_RPC::Stub(channel));
  return stub;
}

ECHO_RPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_echo_(ECHO_RPC_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ECHO_RPC::Stub::echo(::grpc::ClientContext* context, const ::echo::Message& request, ::echo::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::echo::Message, ::echo::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_echo_, context, request, response);
}

void ECHO_RPC::Stub::experimental_async::echo(::grpc::ClientContext* context, const ::echo::Message* request, ::echo::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::echo::Message, ::echo::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_echo_, context, request, response, std::move(f));
}

void ECHO_RPC::Stub::experimental_async::echo(::grpc::ClientContext* context, const ::echo::Message* request, ::echo::Message* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::echo::Message>* ECHO_RPC::Stub::PrepareAsyncechoRaw(::grpc::ClientContext* context, const ::echo::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::echo::Message, ::echo::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::echo::Message>* ECHO_RPC::Stub::AsyncechoRaw(::grpc::ClientContext* context, const ::echo::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncechoRaw(context, request, cq);
  result->StartCall();
  return result;
}

ECHO_RPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ECHO_RPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ECHO_RPC::Service, ::echo::Message, ::echo::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ECHO_RPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::echo::Message* req,
             ::echo::Message* resp) {
               return service->echo(ctx, req, resp);
             }, this)));
}

ECHO_RPC::Service::~Service() {
}

::grpc::Status ECHO_RPC::Service::echo(::grpc::ServerContext* context, const ::echo::Message* request, ::echo::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace echo

